project:
  type: website
  output-dir: docs

website:
  title: "Liesl Eckstrom"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      
  sidebar:
    - id: mini_project1
      title: "Mini Project 1"
      contents:
        - 02_maps_part1.qmd
        - 03_maps_part2.qmd

  page-footer:
    left: |
      &copy; Liesl Eckstrom, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

