---
title: "Squirrels in the United States"
author: "Liesl Eckstrom"
sidebar: false
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library(readr)
library(tidyverse)
library(mdsr)
library(dplyr)
library(ggplot2)
library(maps)
```

```{r, include = FALSE}
squirrel_population_by_state_2024 <- read_csv("squirrel-population-by-state-2024.csv")
```

```{r, include = FALSE}
#| message: false
#| warning: false

us_states <- map_data("state")
head(us_states)
```

```{r, include = FALSE}
us_squirrel<- us_states |>
  mutate(state = title_case_states <- str_to_title(region)) |>
  select(-c(region,subregion)) |>
  inner_join(squirrel_population_by_state_2024) |>
  select(- SquirrelPopulationSpeciesNames)
```

```{r, echo = FALSE}
us_squirrel |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(aes(fill = SquirrelPopulationNumberOfMajorSquirrelSpecies), color = "white", linewidth = 0.4) + 
  labs(fill = "# of Major 
Squirrel 
Species", title = "Number of Major Squirrel Species by State",
caption = "data from: https://worldpopulationreview.com/") +
  # This scales the longitude and latitude so that the shapes look correct.
  coord_map() + 
  # This theme can give you a really clean look!
  theme_void() + 
  # you can change the fill scale for different color schemes.
  scale_fill_continuous(high = "hotpink", low = "pink") 
```

This map of the United States shows the number of major squirrel species that live in each state. Ranging from 2 to 8 many states have a different number of squirrel species that live in them. This data is interesting to know to see what states have suitable environments and proper food supply for squirrels.
